//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Colors = &struct {
	Red   postgres.StringExpression
	Green postgres.StringExpression
	Blue  postgres.StringExpression
}{
	Red:   postgres.NewEnumValue("red"),
	Green: postgres.NewEnumValue("green"),
	Blue:  postgres.NewEnumValue("blue"),
}
