//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Colors string

const (
	Colors_Red   Colors = "red"
	Colors_Green Colors = "green"
	Colors_Blue  Colors = "blue"
)

func (e *Colors) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "red":
		*e = Colors_Red
	case "green":
		*e = Colors_Green
	case "blue":
		*e = Colors_Blue
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Colors enum")
	}

	return nil
}

func (e Colors) String() string {
	return string(e)
}
